# Generated by tools/diaggulp_carve.py — do not edit by hand.
# Puts the carve root (where diaggulp.py lives) on sys.path so the tests
# import the single-module package in-place, without an editable install.
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
